from .connections import FastConnect, Server, Request, Packets

class OEM_P:...

class DIM_P:...

class SecurePacket:...

class EMethod:... # EncryptionMethod

def encrypt_data (data,encyption_method):...

def decrypt_data (data,decryption_key):...
