class Date:...
class Time:...
class Gender:...
class _Gender_Male:...
class _Gender_Female:...
class _Gender_Unknown:...
class DateTime:...
class String:...
class Number:...
class Language:...
class Country:...
class Location:...
class geLocation:...
class File:...
class Directory:...
class Path:...
class FileType:...
class Sigma:...

def new (Type,input):
    return Type(input)

