#include "types.h"

#define OMG_MAX_OBJSIZE
#define _OMGINT_T 
#define _OMGFLOAT_T 
#define _OMGLIST_T 
#define _OMGTUPLE_T 
#define _OMGDICT_T 
#define _OMGSET_T 
#define _OMGBOOL_T 
#define _OMGNONE_T 
#define _OMGBYTE_T 
#define _OMGTYPE_T 
#define _OMGDEC_T 
#define _OMGCLASS_T 
#define _OMGUDC_T 
#define _OMGFUNC_T 
#define _OMGINT_N 
#define _OMGFLOAT_N 
#define _OMGLIST_N 
#define _OMGTUPLE_N 
#define _OMGDICT_N 
#define _OMGSET_N 
#define _OMGBOOL_N 
#define _OMGNONE_N 
#define _OMGBYTE_N 
#define _OMGTYPE_N 
#define _OMGDEC_N
#define _OMGCLASS_N 
#define _OMGUDC_N 
#define _OMGFUNC_N
#define FastDecVar 

#define oMAX_FILE_SIZE 
#define oReadFileMod	
#define oWriteFileMod	
#define oAppendFileMod  
#define oReadBinaryFileMod   
#define oWriteBinaryFileMod  
#define oAppendBinaryFileMod 
#define oFileOpenStandardFunc
#define oDefaultFileMod      
